### ISSUE TITLE
Create JDBC Client

### ISSUE THREAD

**Issue by NassimBtk** [sentrysoftware/jdbc#2]
# Specification

Create a simple client to run JDBC queries, the client will require the following properties:

- String url
- String username
- char[] password
- String sqlQuery
- boolean showWarnings
- int timeout

Create a singleton to manage driver classes loading. A (`DriverLoader`) class that loads drivers only once and manages the loading using a thread safe list.

**Comment by bertysentry** [comment]
Maybe we should return a String[][] (array of rows, each containing an array of columns). Up to the caller to serialize in CSV if required.
Then the `columnSeparator` input is not required.

**Comment by NassimBtk** [comment]
Yes it is better to return a structured table as expected by MetricsHub.
